# Configuration des routes pour l'application Eurovision

# Pages publiques
app_home:
    path: /
    controller: App\Controller\ConnectionController::index
    methods: [GET]

app_vote:
    path: /vote
    controller: App\Controller\VoteController::index
    methods: [GET]

app_results:
    path: /results
    controller: App\Controller\ResultsController::index
    methods: [GET]

# API
api_validate_connection:
    path: /api/validate-connection
    controller: App\Controller\ConnectionController::validateConnection
    methods: [POST]

api_vote:
    path: /api/vote
    controller: App\Controller\VoteController::vote
    methods: [POST]

api_user_votes:
    path: /api/user-votes
    controller: App\Controller\VoteController::getUserVotes
    methods: [GET]

api_results:
    path: /api/results
    controller: App\Controller\ResultsController::getResults
    methods: [GET]

api_teams_stats:
    path: /api/teams-stats
    controller: App\Controller\ResultsController::getTeamsStats
    methods: [GET]